apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gestor-gastro-hml
  namespace: umami-argocd-hml
  labels:
    app.kubernetes.io/name: gestor-gastro
    app.kubernetes.io/part-of: umami-tech
spec:
  project: default
  source:
    repoURL: https://github.com/RaphaelFigueira/umami-gitops.git
    targetRevision: main
    path: clusters/hml/gestor-gastro
  destination:
    server: https://kubernetes.default.svc
    namespace: umami-gestor-gastro-hml
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
