apiVersion: v1
kind: ConfigMap
metadata:
  name: gestor-gastro-shop-config
  namespace: umami-gestor-gastro-hml
  labels:
    app.kubernetes.io/name: gestor-gastro-shop
    app.kubernetes.io/part-of: umami-tech
    umami.tech/environment: hml
data:
  NODE_ENV: production
  VITE_SUPABASE_URL: "[PUBLIC]"
  VITE_SUPABASE_ANON_KEY: "[PUBLIC]"
