apiVersion: v1
kind: ConfigMap
metadata:
  name: gestor-gastro-admin-config
  namespace: umami-gestor-gastro-hml
  labels:
    app.kubernetes.io/name: gestor-gastro-admin
    app.kubernetes.io/part-of: umami-tech
    umami.tech/environment: hml
data:
  NODE_ENV: production
  NEXT_PUBLIC_SUPABASE_URL: "[PUBLIC]"
  NEXT_PUBLIC_SUPABASE_ANON_KEY: "[PUBLIC]"
  NEXTAUTH_URL: https://gestor-gastro-hml.umamitech.net.br/admin
