apiVersion: v1
kind: Secret
metadata:
  name: gestor-gastro-admin-secrets
  namespace: umami-gestor-gastro-hml
  labels:
    app.kubernetes.io/name: gestor-gastro-admin
    app.kubernetes.io/part-of: umami-tech
    umami.tech/environment: hml
type: Opaque
stringData:
  NEXTAUTH_SECRET: "[TODO]"
  SUPABASE_SERVICE_ROLE_KEY: "[TODO]"
  DATABASE_URL: "[TODO]"
